# Generated by Django 5.1.6 on 2025-05-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
