# Generated by Django 5.1.6 on 2025-05-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_time', models.IntegerField()),
                ('pc_time', models.IntegerField()),
                ('mobile_time', models.IntegerField()),
                ('television_time', models.IntegerField()),
            ],
        ),
    ]
