# Generated by Django 5.1.6 on 2025-05-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='user',
            field=models.CharField(default='placeholder_user', max_length=100),
            preserve_default=False,
        ),
    ]
