# Generated by Django 5.1.6 on 2025-05-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0003_time_date_alter_time_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='pc_time',
            new_name='computer_time',
        ),
    ]
