# Generated by Django 5.1.6 on 2025-05-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0005_alter_time_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='user',
            field=models.IntegerField(),
        ),
    ]
