# Generated by Django 5.1.6 on 2025-03-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='password',
            field=models.CharField(default='temporary_password', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='username',
            field=models.CharField(default='temporary_username', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
