# Generated by Django 5.1.6 on 2025-06-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='book',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
